### ISSUE TITLE
v4 typescript compatibility: Could not find file `component.vue?rollup-plugin-vue=script.ts`

### ISSUE THREAD

**Issue by alexsasharegan** [vuejs/rollup-plugin-vue#204]
### Expected behavior

Should work with 3rd party plugins--in this case, `rollup-plugin-typescript2`.

### Actual behavior

Fails to resolve typescript portion of `.vue` file. This issue was first filed in the plugin repo, but @ezolenko was not able to find the issue. It sounds like a breaking plugin api change.

```
[!] (rpt2 plugin) Error: Could not find file: '~/github.com/alexsasharegan/vue-transmit/src/components/VueTransmit.vue.ts?rollup-plugin-vue=script.ts'.
src/components/VueTransmit.vue.ts?rollup-plugin-vue=script.ts
Error: Could not find file: '~/github.com/alexsasharegan/vue-transmit/src/components/VueTransmit.vue.ts?rollup-plugin-vue=script.ts'.
    at getValidSourceFile (~/github.com/alexsasharegan/vue-transmit/node_modules/typescript/lib/typescript.js:103163:23)
    at Object.getEmitOutput (~/github.com/alexsasharegan/vue-transmit/node_modules/typescript/lib/typescript.js:103506:30)
    at ~/github.com/alexsasharegan/vue-transmit/node_modules/rollup-plugin-typescript2/src/index.ts:192:28
    at TsCache.getCompiled (~/github.com/alexsasharegan/vue-transmit/node_modules/rollup-plugin-typescript2/src/tscache.ts:174:27)
    at Object.transform (~/github.com/alexsasharegan/vue-transmit/node_modules/rollup-plugin-typescript2/src/index.ts:190:27)
    at ~/github.com/alexsasharegan/vue-transmit/node_modules/rollup/dist/rollup.js:17508:48
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

### Steps to reproduce the behavior

View the detailed description in the original issue filed with rollup-plugin-typescript2:

https://github.com/ezolenko/rollup-plugin-typescript2/issues/78

**Comment by vankooch** [comment]
I've the same problem here

**Comment by snokier** [comment]
+1

**Comment by snokier** [comment]
has this fixed?

**Comment by alexsasharegan** [comment]
The issue is still open at rollup-plugin-typescript2. Haven't heard much yet if it's been fixed. Sounded like it's an issue there though

**Comment by snokier** [comment]
Thx. Hope we can hear some good news.

**Comment by alexsasharegan** [comment]
I sent the maintainer another ping.

**Comment by vanppo** [comment]
same issue with @rollup/plugin-typescript
