### ISSUE TITLE
VuePlugin is not a function

### ISSUE THREAD

**Issue by sujianqingfeng** [vuejs/rollup-plugin-vue#229]
### Expected behavior
TypeError: vue is not a function
    at Gulp.gulp.task (F:\web_work\vue-componnent-test\gulpfile.js:23:13)
    at module.exports (F:\web_work\vue-componnent-test\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (F:\web_work\vue-componnent-test\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (F:\web_work\vue-componnent-test\node_modules\orchestrator\index.js:214:10)
    at F:\web_work\vue-componnent-test\node_modules\orchestrator\index.js:279:18
    at finish (F:\web_work\vue-componnent-test\node_modules\orchestrator\lib\runTask.js:21:8)
    at F:\web_work\vue-componnent-test\node_modules\orchestrator\lib\runTask.js:52:4
    at f (F:\web_work\vue-componnent-test\node_modules\end-of-stream\node_modules\once\once.js:17:25)
    at Transform.onend (F:\web_work\vue-componnent-test\node_modules\end-of-stream\index.js:31:18)
    at emitNone (events.js:111:20)
    at Transform.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
### Actual behavior
build:dev task error
### Steps to reproduce the behavior
```
const gulp = require('gulp')
const eslint = require('gulp-eslint')
const clear = require('clear')
const { rollup } = require('rollup')
const vue = require('rollup-plugin-vue')
const babel = require('rollup-plugin-babel')
const uglify = require('rollup-plugin-uglify')

const moduleName = 'ComponentTest'
const destName = 'vue-component-test'
// 检测代码风格
gulp.task('lint', () => {
  clear()
  return gulp.src(['**/*.js', '**/*.vue', '!node_modules/**', '!dist/**'])
    .pipe(eslint())
    .pipe(eslint.format())
    .pipe(eslint.failAfterError())
})

// 编译开发版本
gulp.task('build:dev', ['lint'], () => rollup({
  entry: 'lib/index.js',
  plugins: [vue(), babel()]
})
  .then((bundle) => {
    bundle.write({
      moduleName,
      format: 'umd',
      dest: `dist/${destName}.js`,
      sourceMap: true
    })
  }))

// 编译生产版本
gulp.task('build:prod', ['lint'], () => rollup({
  entry: 'lib/index.js',
  plugins: [vue(), babel(), uglify()]
})
  .then((bundle) => {
    bundle.write({
      moduleName,
      format: 'umd',
      dest: `dist/${destName}.js`,
      sourceMap: true
    })
  }))

gulp.task('default', ['lint', 'build:dev'])
gulp.task('build', ['lint', 'build:prod'])
gulp.watch(['**/**.js', '**/**.vue', '!node_modules/**', '!dist/**'], ['default'])
```

**Comment by channg** [comment]
+1

**Comment by znck** [comment]
May be due to some typescript config. I'll check.

**Comment by menangen** [comment]
+1 with 
```javascript
const VuePlugin = require("rollup-plugin-vue");

plugins: [
        VuePlugin(),
        ...
`
