### ISSUE TITLE
use style.postcssPlugins error

### ISSUE THREAD

**Issue by channg** [vuejs/rollup-plugin-vue#230]
```
[ Error: Use process(css).then(cb) to work with async plugins
      at LazyResult.sync (D:\github\luck\node_modules\@vue\component-compiler-utils\node_modules\postcss\lib\lazy-result.js:266:23)
      at LazyResult.stringify (D:\github\luck\node_modules\@vue\component-compiler-utils\node_modules\postcss\lib\lazy-result.js:288:14)
      at LazyResult.get (D:\github\luck\node_modules\@vue\component-compiler-utils\node_modules\postcss\lib\lazy-result.js:337:25)
      at doCompileStyle (D:\github\luck\node_modules\@vue\component-compiler-utils\dist\compileStyle.js:60:22)
      at Object.compileStyle (D:\github\luck\node_modules\@vue\component-compiler-utils\dist\compileStyle.js:8:12)
      at SFCCompiler.compileStyle (D:\github\luck\node_modules\@vue\component-compiler\dist\compiler.js:104:51)
      at input.styles.descriptor.styles.map.style (D:\github\luck\node_modules\rollup-plugin-vue\dist\index.js:104:73)
      at Array.map (<anonymous>)
      at Object.<anonymous> (D:\github\luck\node_modules\rollup-plugin-vue\dist\index.js:104:51)
      at Generator.next (<anonymous>)
      at D:\github\luck\node_modules\rollup-plugin-vue\dist\index.js:7:71
      at Promise (<anonymous>)
      at __awaiter (D:\github\luck\node_modules\rollup-plugin-vue\dist\index.js:3:12)
      at Object.transform (D:\github\luck\node_modules\rollup-plugin-vue\dist\index.js:87:20)
      at D:\github\luck\node_modules\rollup\dist\rollup.js:20780:41
      at <anonymous> ]

```

```
vue({
          style:{
            postcssPlugins:[
              preset()
            ]
          }
        })
```

Then I have another question, I also used rollup-plugin-postcss. Can the style in the .vue file use the configuration in rollup?

**Comment by znck** [comment]
Added support for async postcss plugins in v4.4+
