### ISSUE TITLE
Error: Component <path/name.vue> uses lang html for template, however it is not installed.

### ISSUE THREAD

**Issue by iErik** [vuejs/rollup-plugin-vue#256]
Folks, `rollup-plugin-vue` is giving me the following error when I try to build my app:

```
[!] (VuePlugin plugin) Error: Component /Users/convenia/Documents/Git/legacy-rh/assets/painel/js/pages/menu/node_modules/convenia-components/src/components/CTooltip/index.vue uses lang html for template, however it is not installed.
node_modules/convenia-components/src/components/CTooltip/index.vue
Error: Component /Users/convenia/Documents/Git/legacy-rh/assets/painel/js/pages/menu/node_modules/convenia-components/src/components/CTooltip/index.vue uses lang html for template, however it is not installed.
    at error (/Users/convenia/Documents/Git/legacy-rh/assets/painel/js/pages/menu/node_modules/rollup/dist/rollup.js:3596:30)
    at Object.error (/Users/convenia/Documents/Git/legacy-rh/assets/painel/js/pages/menu/node_modules/rollup/dist/rollup.js:22251:17)
    at input.template.errors.map (/Users/convenia/Documents/Git/legacy-rh/assets/painel/js/pages/menu/node_modules/rollup-plugin-vue/dist/index.js:111:71)
    at Array.map (<anonymous>)
    at Object.<anonymous> (/Users/convenia/Documents/Git/legacy-rh/assets/painel/js/pages/menu/node_modules/rollup-plugin-vue/dist/index.js:111:51)
    at Generator.next (<anonymous>)
    at /Users/convenia/Documents/Git/legacy-rh/assets/painel/js/pages/menu/node_modules/rollup-plugin-vue/dist/index.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/convenia/Documents/Git/legacy-rh/assets/painel/js/pages/menu/node_modules/rollup-plugin-vue/dist/index.js:3:12)
    at Object.transform (/Users/convenia/Documents/Git/legacy-rh/assets/painel/js/pages/menu/node_modules/rollup-plugin-vue/dist/index.js:87:20)
    at /Users/convenia/Documents/Git/legacy-rh/assets/painel/js/pages/menu/node_modules/rollup/dist/rollup.js:21962:25

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Here's my `rollup.config.js`:

```import vue from 'rollup-plugin-vue'
import postcss from 'rollup-plugin-postcss'
import commonjs from 'rollup-plugin-commonjs'
import resolve from 'rollup-plugin-node-resolve'
import sourceMaps from 'rollup-plugin-sourcemaps'
import babel from 'rollup-plugin-babel'
import json from 'rollup-plugin-json'

export default {
  input: 'src/index.js',
  output:
    [{ file: 'dist/menu.umd.js'
     , name: 'dist/menu.umd.js'
     , sourcemap: true
     , format: 'cjs'
     }],

  plugins:
    [
    , vue({ compileTemplate: false })
    , postcss()
    , babel({ externalHelpers: true, runtimeHelpers: true })
    , json()
    , commonjs()
    , resolve({ extensions: [ '.mjs', '.js', '.json', '.node', '.vue', '.scss' ] })
    ]
}
```

And here's the component that's giving me the error:

```vue
<template lang="html">
  <transition name="c-tooltip-show">
    <c-popover
      v-if="show"
      ref="popover"
      v-bind="$attrs"
      :class="['c-tooltip', { '-dark': dark }]"
      @mouseover.stop
    >
      <c-card
        :background-color="dark ? '#121E48' : '#FFF'"
        :style="{ '--tooltip-font-size': `${fontSize}px` }"
        class="card"
        no-hover
        no-border
      >
        <!-- @slot The tooltip's content slot. -->
        <slot />
      </c-card>
    </c-popover>
  </transition>
</template>

<script>
import CPopover from '../CPopover'
import CCard from '../CCard'

/**
 * Tooltip component used by the v-tooltip directive.
 */
export default {
  name: 'CTooltip',
  components: { CPopover, CCard },

  props: {
    /**
     * Whether to show or hide the toolip component.
     */
    show: Boolean,

    /**
     * Makes the toolip bg-color dark.
     */
    dark: Boolean,

    /**
     * The tooltip's font-size
     */
    fontSize: {
      type: Number,
      default: 11
    }
  },

  methods: {
    setPosition () {
      this.$refs.popover && this.$refs.popover.setPosition()
    }
  }
}
</script>
```

**Comment by iErik** [comment]
nvm guise, I just removed the `lang="html"` from the template.

**Comment by iErik** [comment]
u guise r awesome

**Comment by Askerad** [comment]
I would like to reopen this issue, I'm hitting the same wall but removing the "lang" property from the template tag does not fix anything.
