### ISSUE TITLE
img tag error

### ISSUE THREAD

**Issue by XieYuanCode** [vuejs/rollup-plugin-vue#277]
### Version
4.7.2

### Reproduction link
[https://github.com/XieYuanCode/rollup-plugin-vue-bug-reporter/tree/master](https://github.com/XieYuanCode/rollup-plugin-vue-bug-reporter/tree/master)

### Steps to reproduce
1. install dependence

```bat
yarn

#OR

npm install
```

2. run code

```bat
node compile.js
```

### What is expected?
i transfrom a vue file with img tag, and i got this error message

### What is actually happening?
Is this a bug? Or I'm not using it correctly

**Comment by LinusBorg** [comment]
>  i got this error message

What error message?

You are referencing `./sign.png`, but that file doesn't exist. That's an error.

**Comment by XieYuanCode** [comment]
> > i got this error message
> 
> What error message?
> 
> You are referencing `./sign.png`, but that file doesn't exist. That's an error.

The image file exists and I just forgot to upload it to github

**Comment by XieYuanCode** [comment]
> > i got this error message
> 
> What error message?
> 
> You are referencing `./sign.png`, but that file doesn't exist. That's an error.

error message：
```bat
$ node ./compile.js
(node:83671) UnhandledPromiseRejectionWarning: Error: Unexpected character '�' (Note that you need plugins to import files that are not JavaScript)
    at error (/Users/xieyuan/Code/test/node_modules/rollup/dist/rollup.js:3601:30)
    at Module.error (/Users/xieyuan/Code/test/node_modules/rollup/dist/rollup.js:14470:9)
    at tryParse (/Users/xieyuan/Code/test/node_modules/rollup/dist/rollup.js:14390:16)
    at Module.setSource (/Users/xieyuan/Code/test/node_modules/rollup/dist/rollup.js:14664:35)
    at /Users/xieyuan/Code/test/node_modules/rollup/dist/rollup.js:17836:20
    at process.runNextTicks [as _tickCallback] (internal/process/next_tick.js:47:5)
    at Function.Module.runMain (internal/modules/cjs/loader.js:804:11)
    at internal/main/run_main_module.js:21:11
(node:83671) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:83671) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by LinusBorg** [comment]
You will need a rollup plugin to import an image like that. Just like you need a loader in webpack.

https://github.com/rollup/awesome

This is not related to this plugin.
