### ISSUE TITLE
not working with `preserveModules=true`

### ISSUE THREAD

**Issue by 07akioni** [vuejs/rollup-plugin-vue#408]
### Version
```
"@vue/compiler-sfc": "^3.0.2",
"rollup": "^2.32.1",
"rollup-plugin-vue": "^6.0.0-beta.10"
```

### Reproduction link
https://github.com/07akioni/vue3-rollup-test

### Steps to reproduce
follow the link

### What is expected?
not error

### What is actually happening?
```
> test-rollup@1.0.0 build /Users/hrsonion/Development/DevC/tusimple/test-rollup
> rollup -c rollup.config.js


src/RTest.vue → es...
(!) Unused external imports
createVNode imported from external module 'vue' but never used
[!] Error: Invalid substitution ".vue?vue&type=template&id=d21c4c0a" for placeholder "[extname]" in "output.entryFileNames" pattern, can be neither absolute nor relative path.
Error: Invalid substitution ".vue?vue&type=template&id=d21c4c0a" for placeholder "[extname]" in "output.entryFileNames" pattern, can be neither absolute nor relative path.
    at error (/Users/hrsonion/Development/DevC/tusimple/test-rollup/node_modules/rollup/dist/shared/rollup.js:5251:30)
    at /Users/hrsonion/Development/DevC/tusimple/test-rollup/node_modules/rollup/dist/shared/rollup.js:10891:20
    at String.replace (<anonymous>)
    at renderNamePattern (/Users/hrsonion/Development/DevC/tusimple/test-rollup/node_modules/rollup/dist/shared/rollup.js:10885:20)
    at Chunk$1.generateIdPreserveModules (/Users/hrsonion/Development/DevC/tusimple/test-rollup/node_modules/rollup/dist/shared/rollup.js:11151:30)
    at Bundle$1.assignChunkIds (/Users/hrsonion/Development/DevC/tusimple/test-rollup/node_modules/rollup/dist/shared/rollup.js:12407:34)
    at Bundle$1.addFinalizedChunksToBundle (/Users/hrsonion/Development/DevC/tusimple/test-rollup/node_modules/rollup/dist/shared/rollup.js:12370:14)
    at Bundle$1.generate (/Users/hrsonion/Development/DevC/tusimple/test-rollup/node_modules/rollup/dist/shared/rollup.js:12354:24)
    at async handleGenerateWrite (/Users/hrsonion/Development/DevC/tusimple/test-rollup/node_modules/rollup/dist/shared/rollup.js:19927:23)
    at async Promise.all (index 0)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test-rollup@1.0.0 build: `rollup -c rollup.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the test-rollup@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/hrsonion/.npm/_logs/2020-10-31T05_29_44_393Z-debug.log
```

**Comment by 07akioni** [comment]
It seems to have been fixed by e334e8c. Will you release a new version soon?

**Comment by znck** [comment]
Released, please confirm if this is fixed?

P.S.: Accepting a test case PR for this, to avoid regression in the future.
