### ISSUE TITLE
<style src="./test.css"> does not work with css example

### ISSUE THREAD

**Issue by manobi** [vuejs/rollup-plugin-vue#412]
### Version
6.0.0-beta.9

### Reproduction link
[Official rollup-plugin-vue css module example](https://github.com/vuejs/rollup-plugin-vue/tree/09c41b7a4b1ad1119fbfe5031782e5573aecb292/examples/css-modules)

### Steps to reproduce
1. Clone the structure in the link
2. Add a test.css file
3. Reference test.css in App.vue `<style src="./test.css"></style>`

### What is expected?
```
$ rollup -c

App.vue → dist/app.js...
created dist/app.js in 602ms
✨  Done in 2.12s.
```

### What is actually happening?
```
$ rollup -c

App.vue → dist/app.js...
[!] (plugin vue) Error: /private/tmp/vue/test.css is not parsed yet
test.css?vue&type=style&index=0&src&lang.css
Error: /private/tmp/vue/test.css is not parsed yet
    at getDescriptor (/private/tmp/vue/node_modules/rollup-plugin-vue/dist/index.js:261:11)
    at Object.transform (/private/tmp/vue/node_modules/rollup-plugin-vue/dist/index.js:94:36)
    at /private/tmp/vue/node_modules/rollup/dist/shared/rollup.js:18724:25
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

error Command failed with exit code 1.
```

---
After trying to make it work on my own project for hours, I've decided to reproduce in official css module example. The error appeared right in my first attempt, so far I've tracked error until the following function:
https://github.com/vuejs/rollup-plugin-vue/blob/next/src/index.ts#L383

**Comment by manobi** [comment]
The same error happens in the latest v6.0.0-beta.11 version.

Vite seems to support it, would it be possible to borrow the implementation?

**Comment by 416377966** [comment]
same problem, <script lang="ts" src="./index/ts"></script> as well

**Comment by manobi** [comment]
> same problem, <script lang="ts" src="./index/ts"></script> as well

@416377966 do you know if Vite supports it?

**Comment by 416377966** [comment]
> > same problem, <script lang="ts" src="./index/ts"></script> as well
> 
> @416377966 do you know if Vite supports it?

yes, vite supports it. i wrote a rollup config,it doest not work

**Comment by manobi** [comment]
> yes, vite supports it. i wrote a rollup config,it doest not work

I would love to know what part of code make it works in Vite and borrow it to my project.
