### ISSUE TITLE
Examples erroring with latest package versions

### ISSUE THREAD

**Issue by blowsie** [vuejs/rollup-plugin-vue#430]
### Version
5.0.0

### Reproduction link
[https://codesandbox.io/s/elastic-mcnulty-sr0h1?file=/package.json](https://codesandbox.io/s/elastic-mcnulty-sr0h1?file=/package.json)

### Steps to reproduce
 - Replicate https://github.com/vuejs/rollup-plugin-vue/tree/master/cookbook/library but using the latest versions.
 - Run
 - See Error `[!] Error: Identifier directly after number (Note that you need plugins to import files that are not JavaScript)`

### What is expected?
Styles to be built properly

### What is actually happening?
Styles fail
```
1:
2: h1 {
       ^
3:   color: red;
4: }
Error: Identifier directly after number (Note that you need plugins to import files that are not JavaScript)
    at error (C:\Projects\ui\node_modules\rollup\dist\shared\rollup.js:5240:30)
    at Module.error (C:\Projects\ui\node_modules\rollup\dist\shared\rollup.js:9932:16)
    at tryParse (C:\Projects\ui\node_modules\rollup\dist\shared\rollup.js:9791:23)
    at Module.setSource (C:\Projects\ui\node_modules\rollup\dist\shared\rollup.js:10239:19)
    at ModuleLoader.addModuleSource (C:\Projects\ui\node_modules\rollup\dist\shared\rollup.js:18524:20)
```

**Comment by ckvv** [comment]
Why is no one responding after so long?

**Comment by derrickb** [comment]
A way to mitigate this error is to have the PostCSS or CSS plugins in your plugin array. Hope this gets cleared up so this dependency is no longer necessary.

```
import vue from 'rollup-plugin-vue';
import css from 'rollup-plugin-css-only';
...
plugins: [
  vue(),
  css()
]
```
