### ISSUE TITLE
API Docs Errors

### ISSUE THREAD

**Issue by jonataswalker** [vuejs/rollup-plugin-vue#72]
### Steps to reproduce the behavior

Go to http://vuejs.github.io/rollup-plugin-vue/#/en/2.3/?id=template and check `console`.

```
Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null
    at e (https://unpkg.com/docute@2.9.3/dist/docute.js:1:147497)
    at a (https://unpkg.com/docute@2.9.3/dist/docute.js:1:148052)
    at e.default (https://unpkg.com/docute@2.9.3/dist/docute.js:1:120861)
    at jumpToId (https://unpkg.com/docute@2.9.3/dist/docute.js:1:14519)
    at Array.<anonymous> (https://unpkg.com/docute@2.9.3/dist/docute.js:1:3632)
    at j.dispatch (https://unpkg.com/docute@2.9.3/dist/docute.js:1:8967)
    at j.dispatch (https://unpkg.com/docute@2.9.3/dist/docute.js:1:8025)
    at a.n.(anonymous function) (https://unpkg.com/docute@2.9.3/dist/docute.js:1:11258)
    at a.n [as jumpToId] (https://unpkg.com/docute@2.9.3/dist/docute.js:1:20617)
    at a.navigate (https://unpkg.com/docute@2.9.3/dist/docute.js:1:133521)
```

**Comment by znck** [comment]
This is a docute issue.

**Comment by egoist** [comment]
This is because element `#template` does not exist.
